"""Generated callback contracts. Regenerated by py_code_gen.py."""

# catalog_submission_request_callbacks
def catalog_submission_request(component):
    return None

def catalog(component, *, name, locale, currency):
    return None

def categories(component):
    return None

def category_component(component, *, id, name, parent_id):
    return None

def products(component):
    return None

def product_component(component):
    return None

def identity(component, *, sku, name, description, brand):
    return None

def variants(component):
    return None

def variant_component(component, *, sku):
    return None

def price(component, *, amount, currency):
    return None

def attributes(component):
    return None

def attribute_component(component, *, name, value):
    return None

def inventory(component, *, quantity, availability):
    return None

def category_refs(component, *, category_ref):
    return None

def media(component):
    return None

def media_component(component, *, url, kind, alt_text):
    return None

def fulfillment(component, *, requires_shipping, returnable, weight_grams):
    return None

def submission_options(component, *, mode, dry_run):
    return None

# catalog_submission_response_callbacks
def catalog_submission_response(component, *, submission_id, status, accepted_products, rejected_products, message):
    return None

